/*
 Языковые дополнения для easyChem
 International extensions
 */
ChemSys.addDict({
	it: {
		$Native: 'Italiano', $English: 'Italian',

		'Internal error: [msg]': 'Errore interno: [msg]',
		"Unexpected '[C]' in position [pos]": "'[C]' imprevisto in posizione [pos]",
		"Expected '[ok]' instead of '[bad]' in position [pos]": "Prevista '[ok]' invece che '[bad]' nella posizione [pos]",
		"Invalid character '[C]' in position [pos]": "Carattere non valido '[C]' in posizione [pos]",
		"Unknown element character '[C]' in position [pos]": "Carattere non valido '[C]' descrizione del reagente in posizione [pos]",
		"Expected '[C]' in position [pos]": "Richiedi un ['C'] in posizione [pos]",
		"Unknown element '[Elem]' in position [pos]": "Articolo sbagliato '[Elem]' nella posizione [pos]",
		"Browser does not support canvas-graphics": "Browser non supporta canvas-grafica",
		"Formula can not be displayed as text": "Formula non possono essere visualizzati come testo",
		"(s)": "(s)", "(l)": "(l)", "(g)": "(g)",
		'Periodic Table': 'Tavola periodica degli elementi',
		'Table legend': 'Gruppi della tavola periodica',
		Group: 'Gruppo',
		Period: 'Periodo',
		Row: 'Righe',
		'[x]-block': 'Elementi del blocco [x]',
		Lanthanides: 'Lantanoidi',
		Actinides: 'Attinoidi',
		'Alkali metals': 'Metalli alcalini',
		'Alkaline earth metals': 'Metalli alcalino terrosi',
		'Transition metals': 'Metalli del blocco d',
		'Post transition metals': 'Metalli del blocco p',
		Metalloids: 'Semimetalli',
		'Other nonmetals': 'Nonmetalli',
		Halogens: 'Alogeni',
		'Noble gases': 'Gas nobili',
		'Unknown props': 'Proprietà sconosciute',
		H: 'Idrogeno', He: 'Elio', Li: 'Litio', Be: 'Berillio', B: 'Boro', C: 'Carbonio',
		N: 'Azoto', O: 'Ossigeno', F: 'Fluoro', Ne: 'Neon', Na: 'Sodio', Mg: 'Magnesio',
		Al: 'Alluminio', Si: 'Silicio', P: 'Fosforo', S: 'Zolfo', Cl: 'Cloro', Ar: 'Аргон',
		K: 'Potassio', Ca: 'Calcio', Sc: 'Scandio', Ti: 'Titanio', V: 'Vanadio', Cr: 'Cromo',
		Mn: 'Manganese', Fe: 'Ferro', Co: 'Cobalto', Ni: 'Nichel', Cu: 'Rame', Zn: 'Zinco',
		Ga: 'Gallio', Ge: 'Germanio', As: 'Arsenico', Se: 'Selenio', Br: 'Bromo', Kr: 'Kripton',
		Rb: 'Rubidio', Sr: 'Stronzio', Y: 'Ittrio', Zr: 'Zirconio', Nb: 'Niobio', Mo: 'Molibdeno',
		Tc: 'Tecnezio', Ru: 'Rutenio', Rh: 'Rodio', Pd: 'Palladio', Ag: 'Argento', Cd: 'Cadmio',
		In: 'Indio', Sn: 'Stagno', Sb: 'Antimonio', Te: 'Tellurio', I: 'Iodio', Xe: 'Xeno',
		Cs: 'Cesio', Ba: 'Bario', La: 'Lantanio', Ce: 'Cerio', Pr: 'Praseodimio', Nd: 'Neodimio',
		Pm: 'Promezio', Sm: 'Samario', Eu: 'Europio', Gd: 'Gadolinio', Tb: 'Terbio',
		Dy: 'Disprosio', Ho: 'Olmio', Er: 'Erbio', Tm: 'Tulio', Yb: 'Itterbio', Lu: 'Lutezio',
		Hf: 'Afnio', Ta: 'Tantalio', W: 'Tungsteno', Re: 'Renio', Os: 'Osmio', Ir: 'Iridio',
		Pt: 'Platino', Au: 'Oro', Hg: 'Mercurio', Tl: 'Tallio', Pb: 'Piombo', Bi: 'Bismuto',
		Po: 'Polonio', At: 'Astato', Rn: 'Radon', Fr: 'Francio', Ra: 'Radio', Ac: 'Attinio',
		Th: 'Torio', Pa: 'Protoattinio ', U: 'Uranio', Np: 'Nettunio', Pu: 'Plutonio', Am: 'Americio',
		Cm: 'Curio', Bk: 'Berkelio', Cf: 'Californio', Es: 'Einsteinio', Fm: 'Fermio',
		Md: 'Mendelevio', No: 'Nobelio', Lr: 'Laurenzio', Rf: 'Rutherfordio', Db: 'Dubnio',
		Sg: 'Seaborgio', Bh: 'Bohrio', Hs: 'Hassio', Mt: 'Meitnerio', Ds: 'Darmstadtio',
		Rg: 'Roentgenio', Cn: 'Copernicio', Nh: 'Nihonio', Fl: 'Flerovio', Mc: 'Moscovio',
		Lv: 'Livermorio', Ts: 'Tennesso', Og: 'Oganesson'
	},

	'zh': {
		$Native: '中文（简体）', $English: 'Simplified Chinese',
		'Periodic Table': '元素周期表',
		'Table legend': '族 (化学)',
		Group: '族', Period: '周期', Row:'系列',
		'[x]-block': '[x]区元素',
		Lanthanides: '镧系元素', Actinides: '锕系元素',
		'Alkali metals': '碱金属',
		'Alkaline earth metals': '碱土金属',
		'Transition metals': '过渡金属',
		'Post transition metals': '主族金属',
		Metalloids: '类金属',
		'Other nonmetals': '非金属',
		Halogens: '卤素',
		'Noble gases': '稀有气体',
		'Unknown props': '化学特性未知',
		H:'氢', He:'氦', Li:'锂', Be:'铍', B:'硼', C:'碳', N:'氮', O:'氧', F:'氟', Ne:'氖',
		Na:'钠',Mg:'镁', Al:'铝', Si:'硅', P:'磷', S:'硫', Cl:'氯', Ar:'氩', K:'钾', Ca:'钙',
		Sc:'钪', Ti:'钛', V:'钒', Cr:'铬', Mn:'锰', Fe:'铁', Co:'钴', Ni:'镍', Cu:'铜',
		Zn:'锌', Ga:'镓', Ge:'锗', As:'砷', Se:'硒', Br:'溴', Kr:'氪', Rb:'铷', Sr:'锶',
		Y:'钇', Zr:'锆', Nb:'铌', Mo:'钼', Tc:'锝', Ru:'钌', Rh:'铑', Pd:'钯', Ag:'银',
		Cd:'镉', In:'铟', Sn:'锡', Sb:'锑', Te:'碲', I:'碘', Xe:'氙', Cs:'铯', Ba:'钡',
		La:'镧', Ce:'铈', Pr:'镨', Nd:'钕', Pm:'钷', Sm:'钐', Eu:'铕', Gd:'钆', Tb:'铽',
		Dy:'镝', Ho:'钬', Er:'铒', Tm:'铥', Yb:'镱', Lu:'镥', Hf:'铪', Ta:'钽', W:'钨',
		Re:'铼', Os:'锇', Ir:'铱', Pt:'铂', Au:'金', Hg:'汞', Tl:'铊', Pb:'铅', Bi:'铋',
		Po:'钋', At:'砹', Rn:'氡', Fr:'钫', Ra:'镭', Ac:'锕', Th:'钍', Pa:'镤', U:'铀',
		Np:'镎', Pu:'钚', Am:'镅', Cm:'锔', Bk:'锫', Cf:'锎', Es:'锿', Fm:'镄', Md:'钔',
		No:'锘', Lr:'铹', Rf:'炉', Db:'𨧀', Sg:'𨭎', Bh:'𨨏', Hs:'𨭆', Mt:'䥑', Ds:'鐽',
		Rg:'錀', Cn:'鎶', Nh:'鉨', Fl:'鈇', Mc:'镆', Lv:'鉝', Ts:'鿬', Og:'鿫'
	}, // by 陶克清

	'zh-tw': {
		$Native: '中文（繁體）', $English: 'Traditional Chinese',
		'Periodic Table': '元素週期表',
		'Table legend': '族 (化學)',
		Group: '族', Period: '週期', Row:'系列',
		'[x]-block': '[x]區元素',
		Lanthanides: '鑭系元素', Actinides: '錒系元素',
		'Alkali metals': '堿金屬',
		'Alkaline earth metals': '堿土金屬',
		'Transition metals': '過渡金屬',
		'Post transition metals': '主族金屬',
		Metalloids: '類金屬',
		'Other nonmetals': '非金屬',
		Halogens: '鹵素',
		'Noble gases': '稀有氣體',
		'Unknown props': '化學特性未知',
		H:'氫', He:'氦', Li:'鋰', Be:'鈹', B:'硼', C:'碳', N:'氮', O:'氧', F:'氟', Ne:'氖',
		Na:'鈉',Mg:'鎂', Al:'鋁', Si:'矽', P:'磷', S:'硫', Cl:'氯', Ar:'氬', K:'鉀', Ca:'鈣',
		Sc:'鈧', Ti:'鈦', V:'釩', Cr:'鉻', Mn:'錳', Fe:'鐵', Co:'鈷', Ni:'鎳', Cu:'銅',
		Zn:'鋅', Ga:'鎵', Ge:'鍺', As:'砷', Se:'硒', Br:'溴', Kr:'氪', Rb:'銣', Sr:'鍶',
		Y:'釔', Zr:'鋯', Nb:'鈮', Mo:'鉬', Tc:'鍀', Ru:'釕', Rh:'銠', Pd:'鈀', Ag:'銀',
		Cd:'鎘', In:'銦', Sn:'錫', Sb:'銻', Te:'碲', I:'碘', Xe:'氙', Cs:'銫', Ba:'鋇',
		La:'鑭', Ce:'鈰', Pr:'鐠', Nd:'釹', Pm:'鉕', Sm:'釤', Eu:'銪', Gd:'釓', Tb:'鋱',
		Dy:'鏑', Ho:'鈥', Er:'鉺', Tm:'銩', Yb:'鐿', Lu:'鑥', Hf:'鉿', Ta:'鉭', W:'鎢',
		Re:'錸', Os:'鋨', Ir:'銥', Pt:'鉑', Au:'金', Hg:'汞', Tl:'鉈', Pb:'鉛', Bi:'鉍',
		Po:'釙', At:'砹', Rn:'氡', Fr:'鈁', Ra:'鐳', Ac:'錒', Th:'釷', Pa:'鏷', U:'鈾',
		Np:'錼', Pu:'鈈', Am:'鋂', Cm:'鋦', Bk:'錇', Cf:'鉲', Es:'鎄', Fm:'鐨', Md:'鍆',
		No:'鍩', Lr:'鐒', Rf:'鑪', Db:'𨧀', Sg:'𨭎', Bh:'𨨏', Hs:'𨭆', Mt:'䥑', Ds:'鐽',
		Rg:'錀', Cn:'鎶', Nh:'鉨', Fl:'鈇', Mc:'镆', Lv:'鉝', Ts:'鿬', Og:'鿫'
	}, // by 陶克清

	de: {
		$Native: 'Deutsch', $English: 'German',
		'Periodic Table': 'Periodensystem',
		'Table legend': 'Gruppe des Periodensystems',
		Periods: 'Perioden',
		Rows: 'Reihen',
		Lanthanides: 'Lanthanoide',
		Actinides: 'Actinoide',
		'Alkali metals': 'Alkalimetalle',
		'Alkaline earth metals': 'Erdalkalimetalle',
		'Transition metals': 'Übergangsmetalle',
		'Post transition metals': 'Metalle',
		Metalloids: 'Halbmetalle',
		'Other nonmetals': 'Nichtmetalle',
		Halogens: 'Halogene',
		'Noble gases': 'Edelgase',
		'Unknown props': 'Eigenschaften des unbekannten',
		H: 'Wasserstoff', He: 'Helium', Li: 'Lithium', Be: 'Beryllium', B: 'Bor', C: 'Kohlenstoff',
		N: 'Stickstoff', O: 'Sauerstoff', F: 'Fluor', Ne: 'Neon', Na: 'Natrium', Mg: 'Magnesium',
		Al: 'Aluminium', Si: 'Silicium', P: 'Phosphor', S: 'Schwefel', Cl: 'Chlor', Ar: 'Argon',
		K: 'Kalium', Ca: 'Calcium', Sc: 'Scandium', Ti: 'Titan', V: 'Vanadium', Cr: 'Chrom',
		Mn: 'Mangan', Fe: 'Eisen', Co: 'Cobalt', Ni: 'Nickel', Cu: 'Kupfer', Zn: 'Zink',
		Ga: 'Gallium', Ge: 'Germanium', As: 'Arsen', Se: 'Selen', Br: 'Brom', Kr: 'Krypton',
		Rb: 'Rubidium', Sr: 'Strontium', Y: 'Yttrium', Zr: 'Zirconium', Nb: 'Niob', Mo: 'Molybdän',
		Tc: 'Technetium', Ru: 'Ruthenium', Rh: 'Rhodium', Pd: 'Palladium', Ag: 'Silber', Cd: 'Cadmium',
		In: 'Indium', Sn: 'Zinn', Sb: 'Antimon', Te: 'Tellur', I: 'Iod', Xe: 'Xenon',
		Cs: 'Caesium', Ba: 'Barium', La: 'Lanthan', Ce: 'Cer', Pr: 'Praseodym', Nd: 'Neodym',
		Pm: 'Promethium', Sm: 'Samarium', Eu: 'Europium', Gd: 'Gadolinium', Tb: 'Terbium',
		Dy: 'Dysprosium', Ho: 'Holmium', Er: 'Erbium', Tm: 'Thulium', Yb: 'Ytterbium', Lu: 'Lutetium',
		Hf: 'Hafnium', Ta: 'Tantal', W: 'Wolfram', Re: 'Rhenium', Os: 'Osmium', Ir: 'Iridium',
		Pt: 'Platin', Au: 'Gold', Hg: 'Quecksilber', Tl: 'Thallium', Pb: 'Blei', Bi: 'Bismut',
		Po: 'Polonium', At: 'Astat', Rn: 'Radon', Fr: 'Francium', Ra: 'Radium', Ac: 'Actinium',
		Th: 'Thorium', Pa: 'Protactinium', U: 'Uran', Np: 'Neptunium', Pu: 'Plutonium', Am: 'Americium',
		Cm: 'Curium', Bk: 'Berkelium', Cf: 'Californium', Es: 'Einsteinium', Fm: 'Fermium',
		Md: 'Mendelevium', No: 'Nobelium', Lr: 'Lawrencium', Rf: 'Rutherfordium', Db: 'Dubnium',
		Sg: 'Seaborgium', Bh: 'Bohrium', Hs: 'Hassium', Mt: 'Meitnerium', Ds: 'Darmstadtium',
		Rg: 'Roentgenium', Cn: 'Copernicium', Nh: 'Nihonium', Fl: 'Flerovium', Mc: 'Moscovium',
		Lv: 'Livermorium', Ts: 'Tenness', Og: 'Oganesson'
	}, // de
	fr: {
		$Native: 'Français', $English: 'French',
		'Periodic Table': 'Tableau périodique des éléments',
		'Table legend': 'Groupe du tableau périodique',
		'[x]-block': 'bloc [x]',
		Lanthanides: 'Lanthanides',
		Actinides: 'Actinides',
		'Alkali metals': 'Métaux alcalins',
		'Alkaline earth metals': ' Métaux alcalino-terreux',
		'Transition metals': 'Métaux de transition',
		'Post transition metals': 'Métaux pauvres',
		Metalloids: 'Métalloïdes',
		'Other nonmetals': 'Non-métaux',
		Halogens: 'Halogènes',
		'Noble gases': 'Gaz nobles',
		'Unknown props': 'Propriétés sont inconnues',
		H: 'Hydrogène', He: 'Hélium', Li: 'Lithium', Be: 'Béryllium', B: 'Bore', C: 'Carbone',
		N: 'Azote', O: 'Oxygène', F: 'Fluor', Ne: 'Néon', Na: 'Sodium', Mg: 'Magnésium',
		Al: 'Aluminium', Si: 'Silicium', P: 'Phosphore', S: 'Soufre', Cl: 'Chlore', Ar: 'Argon',
		K: 'Potassium', Ca: 'Calcium', Sc: 'Scandium', Ti: 'Titane', V: 'Vanadium', Cr: 'Chrome',
		Mn: 'Manganèse', Fe: 'Fer', Co: 'Cobalt', Ni: 'Nickel', Cu: 'Cuivre', Zn: 'Zinc',
		Ga: 'Gallium', Ge: 'Germanium', As: 'Arsenic', Se: 'Sélénium', Br: 'Brome', Kr: 'Krypton',
		Rb: 'Rubidium', Sr: 'Strontium', Y: 'Yttrium', Zr: 'Zirconium', Nb: 'Niobium', Mo: 'Molybdène',
		Tc: 'Technétium', Ru: 'Ruthénium', Rh: 'Rhodium', Pd: 'Palladium', Ag: 'Argent', Cd: 'Cadmium',
		In: 'Indium', Sn: 'Étain', Sb: 'Antimoine', Te: 'Tellure', I: 'Iode', Xe: 'Xénon',
		Cs: 'Césium', Ba: 'Baryum', La: 'Lanthane', Ce: 'Cérium', Pr: 'Praséodyme', Nd: 'Néodyme',
		Pm: 'Prométhium', Sm: 'Samarium', Eu: 'Europium', Gd: 'Gadolinium', Tb: 'Terbium',
		Dy: 'Dysprosium', Ho: 'Holmium', Er: 'Erbium', Tm: 'Thulium', Yb: 'Ytterbium', Lu: 'Lutécium',
		Hf: 'Hafnium', Ta: 'Tantale', W: 'Tungstène', Re: 'Rhénium', Os: 'Osmium', Ir: 'Iridium',
		Pt: 'Platine', Au: 'Or', Hg: 'Mercure', Tl: 'Thallium', Pb: 'Plomb', Bi: 'Bismuth',
		Po: 'Polonium', At: 'Astate', Rn: 'Radon', Fr: 'Francium', Ra: 'Radium', Ac: 'Actinium',
		Th: 'Thorium', Pa: 'Protactinium ', U: 'Uranium', Np: 'Neptunium', Pu: 'Plutonium', Am: 'Américium',
		Cm: 'Curium', Bk: 'Berkélium', Cf: 'Californium', Es: 'Einsteinium', Fm: 'Fermium',
		Md: 'Mendélévium', No: 'Nobélium', Lr: 'Lawrencium', Rf: 'Rutherfordium', Db: 'Dubnium',
		Sg: 'Seaborgium', Bh: 'Bohrium', Hs: 'Hassium', Mt: 'Meitnérium', Ds: 'Darmstadtium',
		Rg: 'Roentgenium', Cn: 'Copernicium', Nh: 'Nihonium', Fl: 'Flérovium', Mc: 'Moscovium',
		Lv: 'Livermorium', Ts: 'Tennesse', Og: 'Oganesson'
	}, // fr
	es: {
		$Native: 'Español', $English: 'Spanish',
		'Periodic Table': 'Tabla periódica de los elementos',
		'Table legend': 'Grupos de elementos químicos',
		'[x]-block': 'Elementos del bloque [x]',
		Group: 'Grupo',
		Period: 'Período',
		Row: 'Serie',
		Lanthanides: 'Lantánido',
		Actinides: 'Actínido',
		'Alkali metals': 'Metales Alcalinos',
		'Alkaline earth metals': 'Metales Alcalinotérreos',
		'Transition metals': 'Metales de transición',
		'Post transition metals': 'Metales del bloque p',
		Metalloids: 'Metaloides',
		'Other nonmetals': 'No metales',
		Halogens: 'Halógenos',
		'Noble gases': 'Gases nobles',
		'Unknown props': 'Las propiedades son desconocidas',
		H: 'Hidrógeno', He: 'Helio', Li: 'Litio', Be: 'Berilio', B: 'Boro', C: 'Carbono',
		N: 'Nitrógeno', O: 'Oxígeno', F: 'Flúor', Ne: 'Neón', Na: 'Sodio', Mg: 'Magnesio',
		Al: 'Aluminio', Si: 'Silicio', P: 'Fósforo', S: 'Azufre', Cl: 'Cloro', Ar: 'Argón',
		K: 'Potasio', Ca: 'Calcio', Sc: 'Escandio', Ti: 'Titanio', V: 'Vanadio', Cr: 'Cromo',
		Mn: 'Manganeso', Fe: 'Hierro', Co: 'Cobalto', Ni: 'Níquel', Cu: 'Cobre', Zn: 'Cinc',
		Ga: 'Galio', Ge: 'Germanio', As: 'Arsénico', Se: 'Selenio', Br: 'Bromo', Kr: 'Kriptón',
		Rb: 'Rubidio', Sr: 'Estroncio', Y: 'Itrio', Zr: 'Circonio', Nb: 'Niobio', Mo: 'Molibdeno',
		Tc: 'Tecnecio', Ru: 'Rutenio', Rh: 'Rodio', Pd: 'Paladio ', Ag: 'Plata', Cd: 'Cadmio',
		In: 'Indio', Sn: 'Estaño', Sb: 'Antimonio', Te: 'Telurio', I: 'Yodo', Xe: 'Xenón',
		Cs: 'Cesio', Ba: 'Bario', La: 'Lantano', Ce: 'Cerio', Pr: 'Praseodimio', Nd: 'Neodimio',
		Pm: 'Prometio', Sm: 'Samario', Eu: 'Europio', Gd: 'Gadolinio', Tb: 'Terbio',
		Dy: 'Disprosio', Ho: 'Holmio', Er: 'Erbio', Tm: 'Tulio', Yb: 'Iterbio', Lu: 'Lutecio',
		Hf: 'Hafnio', Ta: 'Tantalio', W: 'Wolframio', Re: 'Renio', Os: 'Osmio', Ir: 'Iridio',
		Pt: 'Platino', Au: 'Oro', Hg: 'Mercurio', Tl: 'Talio', Pb: 'Plomo', Bi: 'Bismuto',
		Po: 'Polonio', At: 'Astato', Rn: 'Radón', Fr: 'Francio', Ra: 'Radio', Ac: 'Actinio',
		Th: 'Torio', Pa: 'Protactinio', U: 'Uranio', Np: 'Neptunio', Pu: 'Plutonio', Am: 'Americio',
		Cm: 'Curio', Bk: 'Berkelio', Cf: 'Californio', Es: 'Einstenio', Fm: 'Fermio',
		Md: 'Mendelevio', No: 'Nobelio', Lr: 'Lawrencio', Rf: 'Rutherfordio', Db: 'Dubnio',
		Sg: 'Seaborgio', Bh: 'Bohrio', Hs: 'Hassio', Mt: 'Meitnerio', Ds: 'Darmstadio',
		Rg: 'Roentgenio', Cn: 'Copernicio', Nh: 'Nihonio', Fl: 'Flerovio', Mc: 'Moscovio',
		Lv: 'Livermorio', Ts: 'Teneso', Og: 'Oganesón'
	}, // es
	ja: {
		$Native: '日本語', $English: 'Japan',
		'Periodic Table': '周期表',
		'Table legend': '元素の族',
		'[x]-block': '[x]ブロック元素',
		Group: '族',
		Period: '周期',
		Row: 'Row',
		Lanthanides: 'ランタニド',
		Actinides: 'アクチノイド',
		'Alkali metals': 'アルカリ金属',
		'Alkaline earth metals': 'アルカリ土類金属',
		'Transition metals': '遷移元素',
		'Post transition metals': 'ポスト遷移金属',
		Metalloids: '半金属',
		'Other nonmetals': '非金属元素',
		Halogens: 'ハロゲン',
		'Noble gases': '貴ガス',
		'Unknown props': '未知の性質',
		H: '水素', He: 'ヘリウム', Li: 'リチウム', Be: 'ベリリウム', B: 'ホウ素', C: '炭素',
		N: '窒素', O: '酸素', F: 'フッ素', Ne: 'ネオン', Na: 'ナトリウム', Mg: 'マグネシウム',
		Al: 'アルミニウム', Si: 'ケイ素', P: 'リン', S: '硫黄', Cl: '塩素', Ar: 'アルゴン',
		K: 'カリウム', Ca: 'カルシウム', Sc: 'スカンジウム', Ti: 'チタン', V: 'バナジウム', Cr: 'クロム',
		Mn: 'マンガン', Fe: '鉄', Co: 'コバルト', Ni: 'ニッケル', Cu: '銅', Zn: '亜鉛',
		Ga: 'ガリウム', Ge: 'ゲルマニウム', As: 'ヒ素', Se: 'セレン', Br: '臭素', Kr: 'クリプトン',
		Rb: 'ルビジウム', Sr: 'ストロンチウム', Y: 'イットリウム', Zr: 'ジルコニウム', Nb: 'ニオブ', Mo: 'モリブデン',
		Tc: 'テクネチウム', Ru: 'ルテニウム', Rh: 'ロジウム', Pd: 'パラジウム', Ag: '銀', Cd: 'カドミウム',
		In: 'インジウム', Sn: 'スズ', Sb: 'アンチモン', Te: 'テルル', I: 'ヨウ素', Xe: 'キセノン',
		Cs: 'セシウム', Ba: 'バリウム', La: 'ランタン', Ce: 'セリウム', Pr: 'プラセオジム', Nd: 'ネオジム',
		Pm: 'プロメチウム', Sm: 'サマリウム', Eu: 'ユウロピウム', Gd: 'ガドリニウム', Tb: 'テルビウム',
		Dy: 'ジスプロシウム', Ho: 'ホルミウム', Er: 'エルビウム', Tm: 'ツリウム', Yb: 'イッテルビウム', Lu: 'ルテチウム',
		Hf: 'ハフニウム', Ta: 'タンタル', W: 'タングステン', Re: 'レニウム', Os: 'オスミウム', Ir: 'イリジウム',
		Pt: '白金', Au: '金', Hg: '水銀', Tl: 'タリウム', Pb: '鉛', Bi: 'ビスマス',
		Po: 'ポロニウム', At: 'アスタチン', Rn: 'ラドン', Fr: 'フランシウム', Ra: 'ラジウム', Ac: 'アクチニウム',
		Th: 'トリウム', Pa: 'プロトアクチニウム', U: 'ウラン', Np: 'ネプツニウム', Pu: 'プルトニウム', Am: 'アメリシウム',
		Cm: 'キュリウム', Bk: 'バークリウム', Cf: 'カリホルニウム', Es: 'アインスタイニウム', Fm: 'フェルミウム',
		Md: 'メンデレビウム', No: 'ノーベリウム', Lr: 'ローレンシウム', Rf: 'ラザホージウム', Db: 'ドブニウム',
		Sg: 'シーボーギウム', Bh: 'ボーリウム', Hs: 'ハッシウム', Mt: 'マイトネリウム', Ds: 'ダームスタチウム',
		Rg: 'レントゲニウム', Cn: 'コペルニシウム', Nh: 'ニホニウム', Fl: 'フレロビウム', Mc: 'モスコビウム',
		Lv: 'リバモリウム', Ts: 'テネシン', Og: 'オガネソン'
	}, //ja
	hi: {
		$Native: 'हिन्दी', $English: 'Hindi',
		'Periodic Table': 'आवर्त सारणी',
		'Table legend': 'समूह (आवर्त सारणी)',
		Group: 'समूह', Period: 'आवर्त',
		Lanthanides: 'लैन्थनाइड',
		Actinides: 'ऐक्टिनाइड',
		'Alkali metals': 'क्षार धातुओं',
		'Alkaline earth metals': 'alkaline पृथ्वी धातुओं',
		'Transition metals': 'सन्धिगत तत्व',
		'Post transition metals': 'अन्य धातु',
		Metalloids: 'उपधातुएं',
		'Other nonmetals': 'अन्य अधातु',
		Halogens: 'हैलोजन्स',
		'Noble gases': 'आदर्श गैस',
		'Unknown props': 'अज्ञात गुण',
		H: 'हाइड्रोजन', He: 'हिलियम', Li: 'लिथियम', Be: 'बेरिलियम', B: 'बोरॉन्', C: 'कार्बन',
		N: 'नाइट्रोजन', O: 'ऑक्सीजन', F: 'फ्लोरीन', Ne: 'नियोन', Na: 'सोडियम', Mg: 'मैग्नेशियम',
		Al: 'एल्युमिनियम', Si: 'सिलिकॉन', P: 'फास्फोरस', S: 'गन्धक', Cl: 'क्लोरीन', Ar: 'ऑर्गन',
		K: 'पोटैशियम', Ca: 'कैल्शियम', Sc: 'स्काण्डियम', Ti: 'टाइटानियम', V: 'वनेडियम', Cr: 'क्रोमियम',
		Mn: 'मैंगनीज', Fe: 'लोहा', Co: 'कोबाल्ट', Ni: 'निकेल', Cu: 'ताम्र', Zn: 'जस्ता',
		Ga: 'गैलियम', Ge: 'जर्मेनियम', As: 'आर्सेनिक', Se: 'सेलेनियम', Br: 'ब्रोमिन', Kr: 'क्रिप्टन',
		Rb: 'रुबिडियम', Sr: 'स्ट्रोन्सियम', Y: 'इत्रियम', Zr: 'जर्कोनियम', Nb: 'नायोबियम', Mo: 'मोलिब्डेनम',
		Tc: 'टेक्निशियम', Ru: 'रुथेनियम', Rh: 'रोडियम', Pd: 'पलाडियम', Ag: 'चाँदी', Cd: 'काडमियम',
		In: 'इण्डियम', Sn: 'त्रपु', Sb: 'एन्टिमोनी', Te: 'टेलुरियम', I: 'आयोडिन', Xe: 'ज़ेनान',
		Cs: 'सीज़ियम', Ba: 'बेरियम', La: 'लाञ्थनम', Ce: 'सेरियम', Pr: 'प्रासियोडाइमियम', Nd: 'नियोडाइमियम',
		Pm: 'प्रोमेथियम', Sm: 'सैमरियम', Eu: 'युरोपियम', Gd: 'ग्याडोलिनियम', Tb: 'टर्बियम',
		Dy: 'डिस्प्रोसियम', Ho: 'होल्मियम', Er: 'अर्बियम', Tm: 'थुलियम', Yb: 'यिट्टरबियम', Lu: 'लुटेटियम',
		Hf: 'हाफ्नियम', Ta: 'टाण्टलम', W: 'टंग्स्टन', Re: 'रेनियम', Os: 'अस्मियम', Ir: 'इरिडियम',
		Pt: 'प्लाटिनम', Au: 'सोना', Hg: 'पारा', Tl: 'थैलियम', Pb: 'सीसा', Bi: 'बिस्मथ',
		Po: 'पोलोनियम', At: 'एस्टाटिन', Rn: 'रेडन', Fr: 'फ्रान्सियम', Ra: 'रेडियम', Ac: 'एक्टिनियम',
		Th: 'थोरियम', Pa: 'प्रोटैक्टीनियम ', U: 'युरेनियम', Np: 'नेप्ट्यूनियम', Pu: 'प्लूटोनियम', Am: 'अमेरिशियम',
		Cm: 'क्यूरियम', Bk: 'बर्केलियम', Cf: 'कैलीफोर्नियम', Es: 'आइन्स्टाइनियम', Fm: 'फर्मियम',
		Md: 'मेण्डेलीवियम', No: 'नोबेलियम', Lr: 'लॉरेंशियम', Rf: 'रुथरफोर्डियम', Db: 'डब्नियम',
		Sg: 'सीबोर्गियम', Bh: 'बोरियम', Hs: 'हसियम', Mt: 'मेइट्नेरियम', Ds: 'डार्म्स्टेडशियम',
		Rg: 'रॉन्टजैनियम', Cn: 'उनउनबियम', Nh: 'उनउनट्रियम', Fl: 'Flerovium', Mc: 'Moscovium',
		Lv: 'लिवरमोरियम', Ts: 'Tennessine', Og: 'युनुनोक्टियम'
	}, //hi
	ar: {
		$Native: 'العربية', $English: 'Arabic',
		Group: 'المجموعة', Period: 'الدورة',
		'Periodic Table': 'جدول دوري',
		'Table legend': 'مجموعة جدول دوري',
		Lanthanides: 'لانثينيدات',
		Actinides: 'أكتينيدات',
		'Alkali metals': 'فلز قلوي',
		'Alkaline earth metals': 'فلز قلوي ترابي',
		'Transition metals': 'فلز انتقالي',
		'Post transition metals': 'فلز بعد انتقالي',
		Metalloids: 'شبه فلزات',
		'Other nonmetals': 'لا فلزت أخرى',
		Halogens: 'هالوجين',
		'Noble gases': 'غاز نبيلغاز نبيل',
		'Unknown props': 'الخصائص مجهولة الكيميائية',
		H: 'هيدروجين', He: 'هيليوم', Li: 'ليثيوم', Be: 'بيريليوم', B: 'بورون', C: 'كربون',
		N: 'نيتروجين', O: 'أكسجين', F: 'فلور', Ne: 'نيون', Na: 'صوديوم', Mg: 'مغنسيوم',
		Al: 'ألومنيوم', Si: 'سليكون', P: 'فسفور', S: 'كبريت', Cl: 'كلور', Ar: 'أرغون',
		K: 'بوتاسيوم', Ca: 'كالسيوم', Sc: 'سكانديوم', Ti: 'تيتانيوم', V: 'فاناديوم', Cr: 'كروم',
		Mn: 'منغنيز', Fe: 'حديد', Co: 'كوبالت', Ni: 'نيكل', Cu: 'نحاس', Zn: 'زنك',
		Ga: 'غاليوم', Ge: 'جرمانيوم', As: 'زرنيخ', Se: 'سيلينيوم', Br: 'بروم', Kr: 'كريبتون',
		Rb: 'روبيديوم', Sr: 'سترونشيوم', Y: 'إتريوم', Zr: 'زركونيوم', Nb: 'نيوبيوم', Mo: 'موليبدنوم',
		Tc: 'تكنيشيوم', Ru: 'روثينيوم', Rh: 'روديوم', Pd: 'بالاديوم', Ag: 'فضة', Cd: 'كادميوم',
		In: 'إنديوم', Sn: 'قصدير', Sb: 'إثمد', Te: 'تيلوريوم', I: 'يود', Xe: 'زينون',
		Cs: 'سيزيوم', Ba: 'باريوم', La: 'لانثانوم', Ce: 'سيريوم', Pr: 'براسيوديميوم', Nd: 'نيوديميوم',
		Pm: 'بروميثيوم', Sm: 'ساماريوم', Eu: 'يوروبيوم', Gd: 'غادولينيوم', Tb: 'تيربيوم',
		Dy: 'ديسبروسيوم', Ho: 'هولميوم', Er: 'إربيوم', Tm: 'ثوليوم', Yb: 'إتيربيوم', Lu: 'لوتيشيوم',
		Hf: 'هافنيوم', Ta: 'تانتالوم', W: 'تنغستن', Re: 'رينيوم', Os: 'أوزميوم', Ir: 'إريديوم',
		Pt: 'بلاتين', Au: 'ذهب', Hg: 'زئبق', Tl: 'ثاليوم', Pb: 'رصاص', Bi: 'بزموت',
		Po: 'بولونيوم', At: 'أستاتين', Rn: 'رادون', Fr: 'فرانسيوم', Ra: 'راديوم', Ac: 'أكتينيوم',
		Th: 'ثوريوم', Pa: 'بروتكتينيوم', U: 'يورانيوم', Np: 'نبتونيوم', Pu: 'بلوتونيوم', Am: 'أمريكيوم',
		Cm: 'كوريوم', Bk: 'بركليوم', Cf: 'كاليفورنيوم', Es: 'أينشتاينيوم', Fm: 'فرميوم',
		Md: 'مندليفيوم', No: 'نوبليوم', Lr: 'لورنسيوم', Rf: 'رذرفورديوم', Db: 'دبنيوم',
		Sg: 'سيبورجيوم', Bh: 'بوريوم', Hs: 'هاسيوم', Mt: 'مايتنريوم', Ds: 'دارمشتاتيوم',
		Rg: 'رونتجينيوم', Cn: 'أنون بيوم', Nh: 'نيهونيوم', Fl: 'فليروفيوم', Mc: 'موسكوفيوم',
		Lv: 'ليفرموريوم', Ts: 'تينيسين', Og: 'أوغانيسون'
	}, //ar
	la: {
		$Native: 'Latina', $English: 'Latin',
		'Periodic Table': 'Systema Periodicum',
		'Table legend': 'Series chemica tabellae periodicae',
		Group: 'Grex',
		Period: 'Periodus',
		Row: 'Ordo',
		'[x]-block': '[x]-block',
		Lanthanides: 'Lanthanida',
		Actinides: 'Actinida',
		'Alkali metals': 'Metalla alcalica',
		'Alkaline earth metals': 'Metalla alcalica terrena',
		'Transition metals': 'Metalla transitionis',
		'Post transition metals': 'Metalla post-transitionis',
		Metalloids: 'Metalloides',
		'Other nonmetals': 'Non-metalla',
		Halogens: 'Halogenica',
		'Noble gases': 'Gasia nobilia',
		'Unknown props': 'Unknown proprietates',
		H: 'Hydrogenium', He: 'Helium', Li: 'Lithium', Be: 'Beryllium', B: 'Borium', C: 'Carbonium',
		N: 'Nitrogenium', O: 'Oxygenium', F: 'Fluorum', Ne: 'Neon', Na: 'Natrium', Mg: 'Magnesium',
		Al: 'Aluminium', Si: 'Silicium', P: 'Phosphorus', S: 'Sulphur', Cl: 'Chlorum', Ar: 'Argon',
		K: 'Kalium', Ca: 'Calcium', Sc: 'Scandium', Ti: 'Titanium', V: 'Vanadium', Cr: 'Chromium',
		Mn: 'Manganum', Fe: 'Ferrum', Co: 'Cobaltum', Ni: 'Niccolum', Cu: 'Cuprum', Zn: 'Zincum',
		Ga: 'Gallium', Ge: 'Germanium', As: 'Arsenicum', Se: 'Selenium', Br: 'Bromum', Kr: 'Krypton',
		Rb: 'Rubidium', Sr: 'Strontium', Y: 'Yttrium', Zr: 'Zirconium', Nb: 'Niobium', Mo: 'Molybdenum',
		Tc: 'Technetium', Ru: 'Ruthenium', Rh: 'Rhodium', Pd: 'Palladium', Ag: 'Argentum', Cd: 'Cadmium',
		In: 'Indium', Sn: 'Stannum', Sb: 'Stibium', Te: 'Tellurium', I: 'Iodum', Xe: 'Xenon',
		Cs: 'Caesium', Ba: 'Barium', La: 'Lanthanum', Ce: 'Cerium', Pr: 'Praseodymium', Nd: 'Neodymium',
		Pm: 'Promethium', Sm: 'Samarium', Eu: 'Europium', Gd: 'Gadolinium', Tb: 'Terbium',
		Dy: 'Dysprosium', Ho: 'Holmium', Er: 'Erbium', Tm: 'Thulium', Yb: 'Ytterbium', Lu: 'Lutetium',
		Hf: 'Hafnium', Ta: 'Tantalum', W: 'Wolframium', Re: 'Rhenium', Os: 'Osmium', Ir: 'Iridium',
		Pt: 'Platinum', Au: 'Aurum', Hg: 'Hydrargyrum', Tl: 'Thallium', Pb: 'Plumbum', Bi: 'Bisemutum',
		Po: 'Polonium', At: 'Astatum', Rn: 'Radon', Fr: 'Francium', Ra: 'Radium', Ac: 'Actinium',
		Th: 'Thorium', Pa: 'Protactinium', U: 'Uranium', Np: 'Neptunium', Pu: 'Plutonium', Am: 'Americium',
		Cm: 'Curium', Bk: 'Berkelium', Cf: 'Californium', Es: 'Einsteinium', Fm: 'Fermium',
		Md: 'Mendelevium', No: 'Nobelium', Lr: 'Lawrencium', Rf: 'Rutherfordium', Db: 'Dubnium',
		Sg: 'Seaborgium', Bh: 'Bohrium', Hs: 'Hassium', Mt: 'Meitnerium', Ds: 'Darmstadtium',
		Rg: 'Roentgenium', Cn: 'Copernicium', Nh: 'Nihonium', Fl: 'Flerovium', Mc: 'Moscovium',
		Lv: 'Livermorium', Ts: 'Tennessine', Og: 'Oganesson'
	}, //la
	el: {
		$Native: 'Ελληνικά', $English: 'Greek',
		'Periodic Table': 'Περιοδικός πίνακας των χημικών στοιχείων',
		'Table legend': 'Σειρές του περιοδικού πίνακα',
		Group: 'Ομάδα',
		Period: 'Περίοδος',
		Row: 'σειρά',
		'[x]-block': '[x]-block',
		Lanthanides: 'Λανθανίδες',
		Actinides: 'Ακτινίδες',
		'Alkali metals': 'Αλκαλιμέταλλα',
		'Alkaline earth metals': 'Αλκαλικές γαίες',
		'Transition metals': 'Στοιχεία μετάπτωσης',
		'Post transition metals': 'Φτωχά μέταλλα',
		Metalloids: 'Μεταλλοειδή',
		'Other nonmetals': 'Αμέταλλα',
		Halogens: 'Αλογόνα',
		'Noble gases': 'Ευγενή Αέρια',
		'Unknown props': 'Άγνωστο ιδιότητες',
		H: 'Υδρογόνο', He: 'Ήλιο', Li: 'Λίθιο', Be: 'Βηρύλλιο', B: 'Βόριο', C: 'Άνθρακας',
		N: 'Άζωτο', O: 'Οξυγόνο', F: 'Φθόριο', Ne: 'Νέον', Na: 'Νάτριο', Mg: 'Μαγνήσιο',
		Al: 'Αργίλιο', Si: 'Πυρίτιο', P: 'Φώσφορος', S: 'Θείο', Cl: 'Χλώριο', Ar: 'Αργό',
		K: 'Κάλιο', Ca: 'Ασβέστιο', Sc: 'Σκάνδιο', Ti: 'Τιτάνιο', V: 'Βανάδιο', Cr: 'Χρώμιο',
		Mn: 'Μαγγάνιο', Fe: 'Σίδηρος', Co: 'Κοβάλτιο', Ni: 'Νικέλιο', Cu: 'Χαλκός', Zn: 'Ψευδάργυρος',
		Ga: 'Γάλλιο', Ge: 'Γερμάνιο', As: 'Αρσενικό', Se: 'Σελήνιο', Br: 'Βρώμιο', Kr: 'Κρυπτό',
		Rb: 'Ρουβίδιο', Sr: 'Στρόντιο', Y: 'Ύττριο', Zr: 'Ζιρκόνιο', Nb: 'Νιόβιο', Mo: 'Μολυβδαίνιο',
		Tc: 'Τεχνήτιο', Ru: 'Ρουθήνιο', Rh: 'Ρόδιο', Pd: 'Παλλάδιο', Ag: 'Άργυρος', Cd: 'Κάδμιο',
		In: 'Ίνδιο', Sn: 'Κασσίτερος', Sb: 'Αντιμόνιο', Te: 'Τελλούριο', I: 'Ιώδιο', Xe: 'Ξένο',
		Cs: 'Καίσιο', Ba: 'Βάριο', La: 'Λανθάνιο', Ce: 'Δημήτριο', Pr: 'Πρασινοδύμιο', Nd: 'Νεοδύμιο',
		Pm: 'Προμήθειο', Sm: 'Σαμάριο', Eu: 'Ευρώπιο', Gd: 'Γαδολίνιο', Tb: 'Τέρβιο',
		Dy: 'Δυσπρόσιο', Ho: 'Όλμιο', Er: 'Έρβιο', Tm: 'Θούλιο', Yb: 'Υττέρβιο', Lu: 'Λουτήτιο',
		Hf: 'Άφνιο', Ta: 'Ταντάλιο', W: 'Βολφράμιο', Re: 'Ρήνιο', Os: 'Όσμιο', Ir: 'Ιρίδιο',
		Pt: 'Λευκόχρυσος', Au: 'Χρυσός', Hg: 'Υδράργυρος', Tl: 'Θάλλιο', Pb: 'Μόλυβδος', Bi: 'Βισμούθιο',
		Po: 'Πολώνιο', At: 'Άστατο', Rn: 'Ραδόνιο', Fr: 'Φράγκιο', Ra: 'Ράδιο', Ac: 'Ακτίνιο',
		Th: 'Θόριο', Pa: 'Πρωτακτίνιο ', U: 'Ουράνιο', Np: 'Ποσειδώνιο', Pu: 'Πλουτώνιο', Am: 'Αμερίκιο',
		Cm: 'Κιούριο', Bk: 'Μπερκέλιο', Cf: 'Καλιφόρνιο', Es: 'Αϊνστάνιο', Fm: 'Φέρμιο',
		Md: 'Μεντελέβιο', No: 'Νομπέλιο', Lr: 'Λωρένσιο', Rf: 'Ραδερφόρντιο', Db: 'Ντούμπνιο',
		Sg: 'Σιμπόργκιο', Bh: 'Μπόριο', Hs: 'Χάσιο', Mt: 'Μαϊτνέριο', Ds: 'Νταρμστάντιο',
		Rg: 'Ρεντγκένιο', Cn: 'Κοπερνίκιο', Nh: 'Νιχόνιο', Fl: 'Flerovium', Mc: 'Μοσκόβιο',
		Lv: 'Λιβερμόριο', Ts: 'Τενέσιο', Og: 'Ογκανέσσιο'
	},
	pt: {
		$Native: 'Português', $English: 'Portuguese',
		'Periodic Table': 'Tabela Periódica dos Elementos',
		'Table legend': 'Grupo de elementos químicos',
		Group: 'Grupo',
		Period: 'Periodo',
		Row: 'Série',
		'[x]-block': '[x]-bloco',
		Lanthanides: 'Lantanídios',
		Actinides: 'Actinídios',
		'Alkali metals': 'Metais alcalinos',
		'Alkaline earth metals': 'Metais alcalinoterrosos',
		'Transition metals': 'Metais de transição',
		'Post transition metals': 'Metais representativos',
		Metalloids: 'Semimetais',
		'Other nonmetals': 'Não metais',
		Halogens: 'Halogênios',
		'Noble gases': 'Gases nobres',
		'Unknown props': 'Desconhecidos',
		H: 'Hidrogénio', He: 'Hélio', Li: 'Lítio', Be: 'Berílio', B: 'Boro', C: 'Carbono',
		N: 'Azoto', O: 'Oxigénio', F: 'Flúor', Ne: 'Néon', Na: 'Sódio', Mg: 'Magnésio',
		Al: 'Alumínio', Si: 'Silício', P: 'Fósforo', S: 'Enxofre', Cl: 'Cloro', Ar: 'Árgon',
		K: 'Potássio', Ca: 'Cálcio', Sc: 'Escândio', Ti: 'Titânio', V: 'Vanádio', Cr: 'Crômio',
		Mn: 'Manganês', Fe: 'Ferro', Co: 'Cobalto', Ni: 'Níquel', Cu: 'Cobre', Zn: 'Zinco',
		Ga: 'Gálio', Ge: 'Germânio', As: 'Arsênio', Se: 'Selênio', Br: 'Bromo', Kr: 'Crípton',
		Rb: 'Rubídio', Sr: 'Estrôncio', Y: 'Ítrio', Zr: 'Zircônio', Nb: 'Nióbio', Mo: 'Molibdênio',
		Tc: 'Tecnécio', Ru: 'Rutênio', Rh: 'Ródio', Pd: 'Paládio', Ag: 'Prata', Cd: 'Cádmio',
		In: 'Índio', Sn: 'Estanho', Sb: 'Αντιμόνιο', Te: 'Telúrio', I: 'Iodo', Xe: 'Xenônio',
		Cs: 'Césio', Ba: 'Bário', La: 'Lantânio', Ce: 'Cério', Pr: 'Praseodímio', Nd: 'Neodímio',
		Pm: 'Promécio', Sm: 'Samário', Eu: 'Európio', Gd: 'Gadolínio', Tb: 'Térbio',
		Dy: 'Disprósio', Ho: 'Hólmio', Er: 'Érbio', Tm: 'Túlio', Yb: 'Itérbio', Lu: 'Lutécio',
		Hf: 'Háfnio', Ta: 'Tântalo', W: 'Tungstênio', Re: 'Rênio', Os: 'Ósmio', Ir: 'Irídio',
		Pt: 'Platina', Au: 'Ouro', Hg: 'Mercúrio', Tl: 'Tálio', Pb: 'Chumbo', Bi: 'Bismuto',
		Po: 'Polônio', At: 'Ástato', Rn: 'Rádon', Fr: 'Frâncio', Ra: 'Rádio', Ac: 'Actínio',
		Th: 'Tório', Pa: 'Protactínio ', U: 'Urânio', Np: 'Neptúnio', Pu: 'Plutônio', Am: 'Amerício',
		Cm: 'Cúrio', Bk: 'Berquélio', Cf: 'Califórnio', Es: 'Einstênio', Fm: 'Férmio',
		Md: 'Mendelévio', No: 'Nobélio', Lr: 'Laurêncio', Rf: 'Rutherfórdio', Db: 'Dúbnio',
		Sg: 'Seabórgio', Bh: 'Bóhrio', Hs: 'Hássio', Mt: 'Meitnério', Ds: 'Darmstácio',
		Rg: 'Roentgênio', Cn: 'Copernício', Nh: 'Nihonium', Fl: 'Fleróvio', Mc: 'Moscóvio',
		Lv: 'Livermório', Ts: 'Tenesso', Og: 'Oganesson'
	},
	cs: {
		$Native: 'Čeština', $English: 'Czech',
		'Periodic Table': 'Periodická tabulka',
		'Table legend': 'Skupiny periodické tabulky',
		Group: 'Skupina',
		Period: 'Perioda',
		Row: 'Řada',
		'[x]-block': 'blok [x]',
		Lanthanides: 'Lanthanoidy',
		Actinides: 'Aktinoidy',
		'Alkali metals': 'Alkalické kovy',
		'Alkaline earth metals': 'Kovy alkalických zemin',
		'Transition metals': 'Přechodné kovy',
		'Post transition metals': 'Nepřechodné kovy',
		Metalloids: 'Polokovy',
		'Other nonmetals': 'Nekovy',
		Halogens: 'Halogeny',
		'Noble gases': 'Vzácné plyny',
		'Unknown props': 'neznámé',
		H: 'Vodík', He: 'Helium', Li: 'Lithium', Be: 'Beryllium', B: 'Bor', C: 'Uhlík',
		N: 'Dusík', O: 'Kyslík', F: 'Fluor', Ne: 'Neon', Na: 'Sodík', Mg: 'Hořčík',
		Al: 'Hliník', Si: 'Křemík', P: 'Fosfor', S: 'Síra', Cl: 'Chlor', Ar: 'Argon',
		K: 'Draslík', Ca: 'Vápník', Sc: 'Skandium', Ti: 'Titan', V: 'Vanad', Cr: 'Chrom',
		Mn: 'Mangan', Fe: 'Železo', Co: 'Kobalt', Ni: 'Nikl', Cu: 'Měď', Zn: 'Zinek',
		Ga: 'Gallium', Ge: 'Germanium', As: 'Arsen', Se: 'Selen', Br: 'Brom', Kr: 'Krypton',
		Rb: 'Rubidium', Sr: 'Stroncium', Y: 'Yttrium', Zr: 'Zirkonium', Nb: 'Niob', Mo: 'Molybden',
		Tc: 'Technecium', Ru: 'Ruthenium', Rh: 'Rhodium', Pd: 'Palladium', Ag: 'Stříbro', Cd: 'Kadmium',
		In: 'Indium', Sn: 'Cín', Sb: 'Antimon', Te: 'Tellur', I: 'Jod', Xe: 'Xenon',
		Cs: 'Cesium', Ba: 'Baryum', La: 'Lanthan', Ce: 'Cer', Pr: 'Praseodym', Nd: 'Neodym',
		Pm: 'Promethium', Sm: 'Samarium', Eu: 'Europium', Gd: 'Gadolinium', Tb: 'Terbium',
		Dy: 'Dysprosium', Ho: 'Holmium', Er: 'Erbium', Tm: 'Thulium', Yb: 'Ytterbium', Lu: 'Lutecium',
		Hf: 'Hafnium', Ta: 'Tantal', W: 'Wolfram', Re: 'Rhenium', Os: 'Osmium', Ir: 'Iridium',
		Pt: 'Platina', Au: 'Zlato', Hg: 'Rtuť', Tl: 'Thallium', Pb: 'Olovo', Bi: 'Bismut',
		Po: 'Polonium', At: 'Astat', Rn: 'Radon', Fr: 'Francium', Ra: 'Radium', Ac: 'Aktinium',
		Th: 'Thorium', Pa: 'Protaktinium', U: 'Uran', Np: 'Neptunium', Pu: 'Plutonium', Am: 'Americium',
		Cm: 'Curium', Bk: 'Berkelium', Cf: 'Kalifornium', Es: 'Einsteinium', Fm: 'Fermium',
		Md: 'Mendelevium', No: 'Nobelium', Lr: 'Lawrencium', Rf: 'Rutherfordium', Db: 'Dubnium',
		Sg: 'Seaborgium', Bh: 'Bohrium', Hs: 'Hassium', Mt: 'Meitnerium', Ds: 'Darmstadtium',
		Rg: 'Roentgenium', Cn: 'Copernicium', Nh: 'Nihonium', Fl: 'Flerovium', Mc: 'Moscovium',
		Lv: 'Livermorium', Ts: 'Tennessin', Og: 'Oganesson'
	} // cs by Martin Slavik
});